name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python run_pipeline.py
      - run: python run_compare.py
      - run: python -m src.explain_xgb
      - run: python -m src.score_dataset
      - run: python -m src.calibrate
      - run: python -m src.fairness
